export default {
  state: () => ({
    artistsList: [
      {
        id: "1",
        name: "Alice Phoebe Lou",
        handle: "alicephoebelou",
        genre: ["Indie Pop", "Indie Folk", "Alternative"],
        location: "Berlin / Cape Town",
        image: "/images/artists/alice-phoebe-lou.jpg",
        bio: "Independent singer-songwriter known for her soulful vocals and dreamy indie-folk sound.",
        tracks: [
          {
            id: "t1-1",
            title: "Witches",
            audioUrl: "/audio/songs/alice-phoebe-lou-witches.mp3",
            coverArt: "/images/artists/alice-phoebe-lou.jpg",
          },
          {
            id: "t1-2",
            title: "Open My Door",
            audioUrl: "/audio/songs/alice-phoebe-lou-open-my-door.mp3",
            coverArt: "/images/artists/alice-phoebe-lou.jpg",
          },
          {
            id: "t1-3",
            title: "Touch",
            audioUrl: "/audio/songs/alice-phoebe-lou-touch.mp3",
            coverArt: "/images/artists/alice-phoebe-lou.jpg",
          },
          {
            id: "t1-4",
            title: "Only When I",
            audioUrl: "/audio/songs/alice-phoebe-lou-only-when-i.mp3",
            coverArt: "/images/artists/alice-phoebe-lou.jpg",
          },
          {
            id: "t1-5",
            title: "Angel",
            audioUrl: "/audio/songs/alice-phoebe-lou-angel.mp3",
            coverArt: "/images/artists/alice-phoebe-lou.jpg",
          },
          {
            id: "t1-6",
            title: "Lover // Over the Moon",
            audioUrl: "/audio/songs/alice-phoebe-lou-lover-over-the-moon.mp3",
            coverArt: "/images/artists/alice-phoebe-lou.jpg",
          },
        ],
      },
      {
        id: "2",
        name: "A-Reece",
        handle: "areeecsa",
        genre: ["Hip-Hop"],
        location: "Pretoria",
        image: "/images/artists/a-reece.jpg",
        bio: "Prolific lyricist and leading figure in South African hip hop.",
        tracks: [
          {
            id: "t2-1",
            title: "Four Horsemen",
            audioUrl: "/audio/songs/a-reece-four-horsemen.mp3",
            coverArt: "/images/artists/a-reece.jpg",
          },
          {
            id: "t2-2",
            title: "Activity",
            audioUrl: "/audio/songs/a-reece-activity.mp3",
            coverArt: "/images/artists/a-reece.jpg",
          },
          {
            id: "t2-3",
            title: "Pavlovian Effect",
            audioUrl: "/audio/songs/a-reece-pavlovian-effect.mp3",
            coverArt: "/images/artists/a-reece.jpg",
          },
          {
            id: "t2-4",
            title: "Bojack",
            audioUrl: "/audio/songs/a-reece-bojack.mp3",
            coverArt: "/images/artists/a-reece.jpg",
          },
          {
            id: "t2-5",
            title: "Confused Admiration",
            audioUrl: "/audio/songs/a-reece-confused-admiration.mp3",
            coverArt: "/images/artists/a-reece.jpg",
          },
          {
            id: "t2-6",
            title: "Idgaf",
            audioUrl:
              "/audio/songs/Idgaf (feat. K.Keed & Jay Jody)-a-reece.mp3",
            coverArt: "/images/artists/a-reece.jpg",
          },
        ],
      },
      {
        id: "3",
        name: "Bongeziwe Mabandla",
        handle: "bongeziwe",
        genre: ["Folk"],
        location: "Johannesburg",
        image: "/images/artists/bongeziwe-mabandla.jpg",
        bio: "Acclaimed Afro-folk artist celebrated for his emotive storytelling and Xhosa lyrics.",
        tracks: [
          {
            id: "t3-1",
            title: "Ndokulandela",
            audioUrl: "/audio/songs/bongeziwe-ndokulandela.mp3",
            coverArt: "/images/artists/bongeziwe-mabandla.jpg",
          },
          {
            id: "t3-2",
            title: "salanabani (13.8.18)",
            audioUrl: "/audio/songs/bongeziwe-salanabani.mp3",
            coverArt: "/images/artists/bongeziwe-mabandla.jpg",
          },
          {
            id: "t3-3",
            title: "masiziyekelele (14.11.16)",
            audioUrl: "/audio/songs/bongeziwe-masiziyekelele.mp3",
            coverArt: "/images/artists/bongeziwe-mabandla.jpg",
          },
          {
            id: "t3-4",
            title: "mini esadibana ngayo (#001)",
            audioUrl: "/audio/songs/bongeziwe-mini-esadibana-ngayo.mp3",
            coverArt: "/images/artists/bongeziwe-mabandla.jpg",
          },
          {
            id: "t3-5",
            title: "jikeleza",
            audioUrl: "/audio/songs/bongeziwe-jikeleza.mp3",
            coverArt: "/images/artists/bongeziwe-mabandla.jpg",
          },
          {
            id: "t3-6",
            title: "Yini",
            audioUrl: "/audio/songs/Yini-bongeziwe-mabandla.mp3",
            coverArt: "/images/artists/bongeziwe-mabandla.jpg",
          },
        ],
      },
      {
        id: "4",
        name: "Brendan Peyper",
        handle: "brendanpeyper",
        genre: ["Pop", "Contemporary Country"],
        location: "Bloemfontein",
        image: "/images/artists/brendan-peyper.jpg",
        bio: "Energetic singer-songwriter blending modern pop appeal with country-rock elements.",
        tracks: [
          {
            id: "t4-1",
            title: "H2Hart",
            audioUrl: "/audio/songs/brendan-peyper-h2hart.mp3",
            coverArt: "/images/artists/brendan-peyper.jpg",
          },
          {
            id: "t4-3",
            title: "Rooi Vlag",
            audioUrl: "/audio/songs/brendan-peyper-rooi-vlag.mp3",
            coverArt: "/images/artists/brendan-peyper.jpg",
          },
          {
            id: "t4-4",
            title: "Kyk",
            audioUrl: "/audio/songs/brendan-peyper-kyk.mp3",
            coverArt: "/images/artists/brendan-peyper.jpg",
          },
          {
            id: "t4-5",
            title: "Lentelyf (Omdat Jy Mag)",
            audioUrl: "/audio/songs/brendan-peyper-lentelyf.mp3",
            coverArt: "/images/artists/brendan-peyper.jpg",
          },
          {
            id: "t4-6",
            title: "Soen Soos Wat Jy Dans",
            audioUrl: "/audio/songs/brendan-peyper-soen-soos-wat-jy-dans.mp3",
            coverArt: "/images/artists/brendan-peyper.jpg",
          },
        ],
      },
      {
        id: "5",
        name: "Civil Twilight",
        handle: "civiltwilight",
        genre: ["Alternative Rock", "Art Rock", "Indie Rock"],
        location: "Johannesburg",
        image: "/images/artists/civil-spotlight.jpg",
        bio: "Independent alternative rock group delivering heavy riffs and dynamic hooks.",
        tracks: [
          {
            id: "t5-1",
            title: "Quiet In My Town",
            audioUrl: "/audio/songs/civil-twilight-quiet-in-my-town.mp3",
            coverArt: "/images/artists/civil-spotlight.jpg",
          },
          {
            id: "t5-2",
            title: "Come As You Are",
            audioUrl: "/audio/songs/civil-twilight-come-as-you-are.mp3",
            coverArt: "/images/artists/civil-spotlight.jpg",
          },
          {
            id: "t5-3",
            title: "Holy Dove",
            audioUrl: "/audio/songs/civil-twilight-holy-dove.mp3",
            coverArt: "/images/artists/civil-spotlight.jpg",
          },
          {
            id: "t5-5",
            title: "Holy Weather",
            audioUrl: "/audio/songs/civil-twilight-holy-weather.mp3",
            coverArt: "/images/artists/civil-spotlight.jpg",
          },
          {
            id: "t5-6",
            title: "Fire Escape",
            audioUrl: "/audio/songs/civil-twilight-fire-escape.mp3",
            coverArt: "/images/artists/civil-spotlight.jpg",
          },
        ],
      },
      {
        id: "6",
        name: "CrashCarBurn",
        handle: "crashcarburn",
        genre: ["Pop-punk", "Power Pop", "Alternative Rock"],
        location: "Johannesburg",
        image: "/images/artists/crashcarburn.jpg",
        bio: "Veteran South African rock band known for high-octane performances.",
        tracks: [
          {
            id: "t6-1",
            title: "Serenade",
            audioUrl: "/audio/songs/crashcarburn-serenade.mp3",
            coverArt: "/images/artists/crashcarburn.jpg",
          },
          {
            id: "t6-2",
            title: "Long Live Tonight",
            audioUrl: "/audio/songs/crashcarburn-long-live-tonight.mp3",
            coverArt: "/images/artists/crashcarburn.jpg",
          },
          {
            id: "t6-3",
            title: "Free Fallin'",
            audioUrl: "/audio/songs/crashcarburn-free-fallin.mp3",
            coverArt: "/images/artists/crashcarburn.jpg",
          },
          {
            id: "t6-4",
            title: "Stay",
            audioUrl: "/audio/songs/crashcarburn-stay.mp3",
            coverArt: "/images/artists/crashcarburn.jpg",
          },
          {
            id: "t6-5",
            title: "Don't Break",
            audioUrl: "/audio/songs/crashcarburn-dont-break.mp3",
            coverArt: "/images/artists/crashcarburn.jpg",
          },
          {
            id: "t6-6",
            title: "Don't It Feel Good?",
            audioUrl: "/audio/songs/crashcarburn-dont-it-feel-good.mp3",
            coverArt: "/images/artists/crashcarburn.jpg",
          },
        ],
      },
      {
        id: "7",
        name: "Da Capo",
        handle: "dacapo",
        genre: ["Dance/Electronic", "Amapiano"],
        location: "Polokwane",
        image: "/images/Da Capo.png",
        bio: "Renowned DJ and producer shaping the deep house and afro-house landscape globally.",
        tracks: [
          {
            id: "t7-1",
            title: "Secret ID",
            audioUrl: "/audio/songs/da-capo-secret-id.mp3",
            coverArt: "/images/Da Capo.png",
          },
          {
            id: "t7-2",
            title: "Afrika",
            audioUrl: "/audio/songs/da-capo-afrika.mp3",
            coverArt: "/images/Da Capo.png",
          },
          {
            id: "t7-3",
            title: "Dance In Villa",
            audioUrl: "/audio/songs/da-capo-dance-in-villa.mp3",
            coverArt: "/images/Da Capo.png",
          },
          {
            id: "t7-4",
            title: "I Choose To Stay",
            audioUrl: "/audio/songs/da-capo-i-choose-to-stay.mp3",
            coverArt: "/images/Da Capo.png",
          },
          {
            id: "t7-5",
            title: "Meet Me In Africa",
            audioUrl: "/audio/songs/da-capo-meet-me-in-africa.mp3",
            coverArt: "/images/Da Capo.png",
          },
          {
            id: "t7-6",
            title: "A Prayer For All My Countrymen",
            audioUrl: "/audio/songs/da-capo-a-prayer-for-all-my-countrymen.mp3",
            coverArt: "/images/Da Capo.png",
          },
        ],
      },
      {
        id: "8",
        name: "Halo Yagami",
        handle: "haloyagami",
        genre: ["Experimental R&B", "Soul"],
        location: "Johannesburg",
        image: "/images/artists/halo-yagami.jpg",
        bio: "Innovative artist pushing the boundaries of sound design and modern rap.",
        tracks: [
          {
            id: "t8-1",
            title: "Uyikhokonke",
            audioUrl: "/audio/songs/halo-yagami-uyikhokonke.mp3",
            coverArt: "/images/artists/halo-yagami.jpg",
          },
          {
            id: "t8-2",
            title: "432",
            audioUrl: "/audio/songs/halo-yagami-432.mp3",
            coverArt: "/images/artists/halo-yagami.jpg",
          },
          {
            id: "t8-3",
            title: "Nyamazane",
            audioUrl: "/audio/songs/halo-yagami-nyamazane.mp3",
            coverArt: "/images/artists/halo-yagami.jpg",
          },
          {
            id: "t8-4",
            title: "Alive",
            audioUrl: "/audio/songs/halo-yagami-alive.mp3",
            coverArt: "/images/artists/halo-yagami.jpg",
          },
          {
            id: "t8-5",
            title: "Phresha",
            audioUrl: "/audio/songs/halo-yagami-phresha.mp3",
            coverArt: "/images/artists/halo-yagami.jpg",
          },
          {
            id: "t8-6",
            title: "Safari",
            audioUrl: "/audio/songs/halo-yagami-safari.mp3",
            coverArt: "/images/artists/halo-yagami.jpg",
          },
        ],
      },
      {
        id: "9",
        name: "Hunter Rose",
        handle: "hunterrose",
        genre: ["Soul", "Jazz", "R&B"],
        location: "Cape Town",
        image: "/images/artists/hunter-rose.jpg",
        bio: "Sensational R&B vocal talent delivering lush harmonies and groovy beats.",
        tracks: [
          {
            id: "t9-1",
            title: "Seaside Dreams",
            audioUrl: "/audio/songs/hunter-rose-seaside-dreams.mp3",
            coverArt: "/images/artists/hunter-rose.jpg",
          },
          {
            id: "t9-2",
            title: "Love Birds",
            audioUrl: "/audio/songs/hunter-rose-lovebirds.mp3",
            coverArt: "/images/artists/hunter-rose.jpg",
          },
          {
            id: "t9-3",
            title: "Fine Wine",
            audioUrl: "/audio/songs/hunter-rose-fine-wine.mp3",
            coverArt: "/images/artists/hunter-rose.jpg",
          },
          {
            id: "t9-4",
            title: "TONIGHT?",
            audioUrl: "/audio/songs/hunter-rose-tonight.mp3",
            coverArt: "/images/artists/hunter-rose.jpg",
          },
          {
            id: "t9-5",
            title: "Get It",
            audioUrl: "/audio/songs/hunter-rose-get-it.mp3",
            coverArt: "/images/artists/hunter-rose.jpg",
          },
          {
            id: "t9-6",
            title: "TIME",
            audioUrl: "/audio/songs/hunter-rose-time.mp3",
            coverArt: "/images/artists/hunter-rose.jpg",
          },
        ],
      },
      {
        id: "10",
        name: "Internet Girl",
        handle: "internetgirl",
        genre: ["Indie", "Garage-Rock"],
        location: "South Africa",
        image: "/images/artists/internet-girl.jpg",
        bio: "Genre-bending underground collective crafting glitchy, high-energy alt sounds.",
        tracks: [
          {
            id: "t10-1",
            title: "PULL UP",
            audioUrl: "/audio/songs/internet-girl-pull-up.mp3",
            coverArt: "/images/artists/internet-girl.jpg",
          },
          {
            id: "t10-2",
            title: "I CHANGED (I'M UP)",
            audioUrl: "/audio/songs/internet-girl-i-changed.mp3",
            coverArt: "/images/artists/internet-girl.jpg",
          },
          {
            id: "t10-3",
            title: "COKEHEAD",
            audioUrl: "/audio/songs/internet-girl-cokehead.mp3",
            coverArt: "/images/artists/internet-girl.jpg",
          },
          {
            id: "t10-4",
            title: "F all ur Friends",
            audioUrl: "/audio/songs/internet-girl-f-all-ur-friends.mp3",
            coverArt: "/images/artists/internet-girl.jpg",
          },
          {
            id: "t10-5",
            title: "NEEDY",
            audioUrl: "/audio/songs/internet-girl-needy.mp3",
            coverArt: "/images/artists/internet-girl.jpg",
          },
          {
            id: "t10-6",
            title: "dumb party",
            audioUrl: "/audio/songs/internet-girl-dumb-party.mp3",
            coverArt: "/images/artists/internet-girl.jpg",
          },
        ],
      },
      {
        id: "11",
        name: "Jamali",
        handle: "jamali",
        genre: ["R&B", "Afropop"],
        location: "Johannesburg",
        image: "/images/Jamali.png",
        bio: "Iconic South African pop-R&B trio celebrated for timeless vocal harmonies.",
        tracks: [
          {
            id: "t11-1",
            title: "Maisha",
            audioUrl: "/audio/songs/jamali-maisha.mp3",
            coverArt: "/images/Jamali.png",
          },
          {
            id: "t11-2",
            title: "Incurable",
            audioUrl: "/audio/songs/jamali-incurable.mp3",
            coverArt: "/images/Jamali.png",
          },
          {
            id: "t11-4",
            title: "Skut Julle Lywe",
            audioUrl: "/audio/songs/jamali-skut-julle-lywe.mp3",
            coverArt: "/images/Jamali.png",
          },
          {
            id: "t11-5",
            title: "Secrets",
            audioUrl: "/audio/songs/jamali-secrets.mp3",
            coverArt: "/images/Jamali.png",
          },
          {
            id: "t11-6",
            title: "Everytime",
            audioUrl: "/audio/songs/jamali-everytime.mp3",
            coverArt: "/images/Jamali.png",
          },
        ],
      },
      {
        id: "12",
        name: "Lordkez",
        handle: "lordkez",
        genre: ["R&B", "Neo-Soul"],
        location: "Johannesburg",
        image: "/images/artists/lordkez.jpg",
        bio: "Versatile singer, songwriter, and poet creating introspective, moody soundscapes.",
        tracks: [
          {
            id: "t12-1",
            title: "Aweh",
            audioUrl: "/audio/songs/lordkez-aweh.mp3",
            coverArt: "/images/artists/lordkez.jpg",
          },
          {
            id: "t12-3",
            title: "belladonna",
            audioUrl: "/audio/songs/lordkez-belladonna.mp3",
            coverArt: "/images/artists/lordkez.jpg",
          },
          {
            id: "t12-4",
            title: "Enthralled",
            audioUrl: "/audio/songs/lordkez-enthralled.mp3",
            coverArt: "/images/artists/lordkez.jpg",
          },
          {
            id: "t12-5",
            title: "Confessions",
            audioUrl: "/audio/songs/lordkez-confessions.mp3",
            coverArt: "/images/artists/lordkez.jpg",
          },
          {
            id: "t12-6",
            title: "22",
            audioUrl: "/audio/songs/lordkez-22.mp3",
            coverArt: "/images/artists/lordkez.jpg",
          },
          {
            id: "t12-7",
            title: "GROOVE99",
            audioUrl: "/audio/songs/lordkez-groove99.mp3",
            coverArt: "/images/artists/lordkez.jpg",
          },
        ],
      },
      {
        id: "13",
        name: "Moonchild Sanelly",
        handle: "moonchildsanelly",
        genre: ["Future Ghetto Funk"],
        location: "Johannesburg",
        image: "/images/Moonchild Sanelly.png",
        bio: "Globally acclaimed singer and dancer known for her signature blue hair and high-energy persona.",
        tracks: [
          {
            id: "t13-1",
            title: "Demon",
            audioUrl: "/audio/songs/moonchild-sanelly-demon.mp3",
            coverArt: "/images/Moonchild Sanelly.png",
          },
          {
            id: "t13-2",
            title: "With Love To An Ex",
            audioUrl: "/audio/songs/moonchild-sanelly-with-love-to-an-ex.mp3",
            coverArt: "/images/Moonchild Sanelly.png",
          },
          {
            id: "t13-3",
            title: "Big Man",
            audioUrl: "/audio/songs/moonchild-sanelly-big-man.mp3",
            coverArt: "/images/Moonchild Sanelly.png",
          },
          {
            id: "t13-4",
            title: "Kokokokoko",
            audioUrl: "/audio/songs/moonchild-sanelly-kokokokoko.mp3",
            coverArt: "/images/Moonchild Sanelly.png",
          },
          {
            id: "t13-5",
            title: "Falling",
            audioUrl: "/audio/songs/moonchild-sanelly-falling.mp3",
            coverArt: "/images/Moonchild Sanelly.png",
          },
          {
            id: "t13-6",
            title: "MY POWER",
            audioUrl: "/audio/songs/moonchild-sanelly-my-power.mp3",
            coverArt: "/images/Moonchild Sanelly.png",
          },
        ],
      },
      {
        id: "14",
        name: "Springbok Nude Girls",
        handle: "springboknudegirls",
        genre: ["Alternative Rock", "Pop-Rock"],
        location: "Stellenbosch",
        image: "/images/Springbok Nude Girls.png",
        bio: "Legendary South African rock heavyweights pioneering alternative music since the 90s.",
        tracks: [
          {
            id: "t14-1",
            title: "Blue Eyes",
            audioUrl: "/audio/songs/springbok-nude-girls-blue-eyes.mp3",
            coverArt: "/images/Springbok Nude Girls.png",
          },
          {
            id: "t14-2",
            title: "Genie",
            audioUrl: "/audio/songs/springbok-nude-girls-genie.mp3",
            coverArt: "/images/Springbok Nude Girls.png",
          },
          {
            id: "t14-3",
            title: "Bubblegum On My Boots",
            audioUrl: "/audio/songs/springbok-nude-girls-bubblegum.mp3",
            coverArt: "/images/Springbok Nude Girls.png",
          },
          {
            id: "t14-4",
            title: "Giant Love Affair",
            audioUrl: "/audio/songs/springbok-nude-girls-giant-love-affair.mp3",
            coverArt: "/images/Springbok Nude Girls.png",
          },
          {
            id: "t14-5",
            title: "Get the Picture",
            audioUrl: "/audio/songs/springbok-nude-girls-get-the-picture.mp3",
            coverArt: "/images/Springbok Nude Girls.png",
          },
          {
            id: "t14-6",
            title: "SA Tan On The Beaches",
            audioUrl: "/audio/songs/springbok-nude-girls-sa-tan.mp3",
            coverArt: "/images/Springbok Nude Girls.png",
          },
        ],
      },
      {
        id: "15",
        name: "The Black Cat Bones",
        handle: "theblackcatbones",
        genre: ["Rock", "Blues", "Country", "Folk"],
        location: "Pretoria",
        image: "/images/artists/the-black-cat-bones.jpg",
        bio: "Raw, gritty blues-rock outfit delivering high-power authentic musicianship.",
        tracks: [
          {
            id: "t15-1",
            title: "Hemingway",
            audioUrl: "/audio/songs/the-black-cat-bones-hemingway.mp3",
            coverArt: "/images/artists/the-black-cat-bones.jpg",
          },
          {
            id: "t15-2",
            title: "Dearly Beloved",
            audioUrl: "/audio/songs/the-black-cat-bones-dearly-beloved.mp3",
            coverArt: "/images/artists/the-black-cat-bones.jpg",
          },
          {
            id: "t15-3",
            title: "Don't Wake The Scarecrow",
            audioUrl: "/audio/songs/the-black-cat-bones-dont-wake.mp3",
            coverArt: "/images/artists/the-black-cat-bones.jpg",
          },
          {
            id: "t15-6",
            title: "The Well",
            audioUrl: "/audio/songs/the-black-cat-bones-the-well.mp3",
            coverArt: "/images/artists/the-black-cat-bones.jpg",
          },
        ],
      },
      {
        id: "16",
        name: "The Dirty Skirts",
        handle: "thedirtyskirts",
        genre: ["Indie Rock", "Alternative Rock"],
        location: "Cape Town",
        image: "/images/artists/the-dirty-skirts.jpg",
        bio: "Award-winning indie rock band famous for electrifying live shows and anthemic hooks.",
        tracks: [
          {
            id: "t16-1",
            title: "Daddy Don't Disco",
            audioUrl: "/audio/songs/the-dirty-skirts-daddy-dont-disco.mp3",
            coverArt: "/images/artists/the-dirty-skirts.jpg",
          },
          {
            id: "t16-2",
            title: "Strike The Match",
            audioUrl: "/audio/songs/the-dirty-skirts-strike-the-match.mp3",
            coverArt: "/images/artists/the-dirty-skirts.jpg",
          },
          {
            id: "t16-3",
            title: "Home Wrecker",
            audioUrl: "/audio/songs/the-dirty-skirts-home-wrecker.mp3",
            coverArt: "/images/artists/the-dirty-skirts.jpg",
          },
          {
            id: "t16-4",
            title: "Rolling Like Thunder",
            audioUrl: "/audio/songs/the-dirty-skirts-rolling-like-thunder.mp3",
            coverArt: "/images/artists/the-dirty-skirts.jpg",
          },
          {
            id: "t16-5",
            title: "Can't Remember Your Name",
            audioUrl: "/audio/songs/the-dirty-skirts-cant-remember.mp3",
            coverArt: "/images/artists/the-dirty-skirts.jpg",
          },
        ],
      },
      {
        id: "17",
        name: "The Parlotones",
        handle: "theparlotones",
        genre: ["Indie Rock", "Alternative Rock", "Pop Rock"],
        location: "Johannesburg",
        image: "/images/artists/the-parlotones.jpg",
        bio: "Multi-platinum selling indie rock band with iconic cinematic sound and grand melodic structures.",
        tracks: [
          {
            id: "t17-1",
            title: "Colourful",
            audioUrl: "/audio/songs/the-parlotones-colourful.mp3",
            coverArt: "/images/artists/the-parlotones.jpg",
          },
          {
            id: "t17-2",
            title: "I'll Be There",
            audioUrl: "/audio/songs/the-parlotones-ill-be-there.mp3",
            coverArt: "/images/artists/the-parlotones.jpg",
          },
          {
            id: "t17-3",
            title: "Giant Mistake",
            audioUrl: "/audio/songs/the-parlotones-giant-mistake.mp3",
            coverArt: "/images/artists/the-parlotones.jpg",
          },
          {
            id: "t17-4",
            title: "I'm Only Human",
            audioUrl: "/audio/songs/the-parlotones-im-only-human.mp3",
            coverArt: "/images/artists/the-parlotones.jpg",
          },
          {
            id: "t17-5",
            title: "Life In a Jar",
            audioUrl: "/audio/songs/the-parlotones-life-in-a-jar.mp3",
            coverArt: "/images/artists/the-parlotones.jpg",
          },
          {
            id: "t17-6",
            title: "Come Together",
            audioUrl: "/audio/songs/the-parlotones-come-together.mp3",
            coverArt: "/images/artists/the-parlotones.jpg",
          },
        ],
      },
      {
        id: "18",
        name: "Usimamane",
        handle: "usimamane",
        genre: ["Hip-Hop/Rap"],
        location: "Durban",
        image: "/images/artists/usimamane.jpg",
        bio: "Pioneering new wave rap artist from South Africa making massive waves.",
        tracks: [
          {
            id: "t18-1",
            title: "Soft",
            audioUrl: "/audio/songs/Soft-usimamane.mp3",
            coverArt: "/images/artists/usimamane.jpg",
          },
          {
            id: "t18-2",
            title: "Anthem",
            audioUrl: "/audio/songs/Anthem-usimamane.mp3",
            coverArt: "/images/artists/usimamane.jpg",
          },
          {
            id: "t18-3",
            title: "Wola",
            audioUrl: "/audio/songs/Wola-usimamane.mp3",
            coverArt: "/images/artists/usimamane.jpg",
          },
          {
            id: "t18-4",
            title: "Star",
            audioUrl: "/audio/songs/Star-usimamane.mp3",
            coverArt: "/images/artists/usimamane.jpg",
          },
          {
            id: "t18-5",
            title: "21",
            audioUrl: "/audio/songs/21-usimamane.mp3",
            coverArt: "/images/artists/usimamane.jpg",
          },
          {
            id: "t18-6",
            title: "Uphambene",
            audioUrl: "/audio/songs/Uphambene-usimamane.mp3",
            coverArt: "/images/artists/usimamane.jpg",
          },
        ],
      },
      {
        id: "19",
        name: "Vigro Deep",
        handle: "vigrodeep",
        genre: ["Amapiano"],
        location: "Pretoria",
        image: "/images/artists/vigro-deep.jpg",
        bio: "Child prodigy and trailblazing producer driving the evolution of Amapiano.",
        tracks: [
          {
            id: "t19-1",
            title: "Bhampa",
            audioUrl:
              "/audio/songs/Vigro Deep, Zee Nxumalo, Ch'cco - Bhampa.mp3",
            coverArt: "/images/artists/vigro-deep.jpg",
          },
          {
            id: "t19-2",
            title: "Ghost Producer",
            audioUrl: "/audio/songs/Ghost Producer-vigro-deep.mp3",
            coverArt: "/images/artists/vigro-deep.jpg",
          },
          {
            id: "t19-3",
            title: "Uyaganga 2.0",
            audioUrl:
              "/audio/songs/Uyaganga 2.0 (Official Audio)-vigro-deep.mp3",
            coverArt: "/images/artists/vigro-deep.jpg",
          },
          {
            id: "t19-4",
            title: "Nomsa",
            audioUrl: "/audio/songs/Vigro Deep, Freddy K - Nomsa.mp3",
            coverArt: "/images/artists/vigro-deep.jpg",
          },
          {
            id: "t19-5",
            title: "Mandebi",
            audioUrl: "/audio/songs/Vigro Deep, Freddy K - Mandebi.mp3",
            coverArt: "/images/artists/vigro-deep.jpg",
          },
          {
            id: "t19-6",
            title: "There's Alot Going On",
            audioUrl:
              "/audio/songs/Vigro Deep, Freddy K - There's Alot Going On.mp3",
            coverArt: "/images/artists/vigro-deep.jpg",
          },
        ],
      },
      {
        id: "20",
        name: "Walk These Skies",
        handle: "walktheseskies",
        genre: ["Modern Metalcore", "Deathcore"],
        location: "Cape Town",
        image: "/images/artists/walk-these-skies.jpg",
        bio: "Melodic rock group known for soaring guitar leads and emotional intensity.",
        tracks: [
          {
            id: "t20-1",
            title: "Godforsaken",
            audioUrl:
              "/audio/songs/Walk These Skies - Godforsaken (Official Music Video).mp3",
            coverArt: "/images/artists/walk-these-skies.jpg",
          },
          {
            id: "t20-2",
            title: "The Bottom",
            audioUrl: "/audio/songs/The Bottom.mp3",
            coverArt: "/images/artists/walk-these-skies.jpg",
          },
          {
            id: "t20-3",
            title: "Cyanide Milkshake",
            audioUrl: "/audio/songs/Cyanide Milkshake.mp3",
            coverArt: "/images/artists/walk-these-skies.jpg",
          },
          {
            id: "t20-4",
            title: "All The Same",
            audioUrl: "/audio/songs/All The Same.mp3",
            coverArt: "/images/artists/walk-these-skies.jpg",
          },
          {
            id: "t20-5",
            title: "Condemned",
            audioUrl: "/audio/songs/Condemned.mp3",
            coverArt: "/images/artists/walk-these-skies.jpg",
          },
          {
            id: "t20-6",
            title: "Tetracycline Injection",
            audioUrl: "/images/artists/Tetracycline Injection.mp3",
            coverArt: "/images/artists/walk-these-skies.jpg",
          },
        ],
      },
      {
        id: "21",
        name: "Will Linley",
        handle: "willlinley",
        genre: ["Pop"],
        location: "Cape Town",
        image: "/images/artists/will-linley.jpg",
        bio: "Viral pop singer-songwriter crafting infectious, heartfelt pop tracks.",
        tracks: [
          {
            id: "t21-1",
            title: "Last Call",
            audioUrl: "/audio/songs/Last Call-will-linley.mp3",
            coverArt: "/images/artists/will-linley.jpg",
          },
          {
            id: "t21-2",
            title: "Holding The Line",
            audioUrl: "/audio/songs/Holding The Line-will-linley.mp3",
            coverArt: "/images/artists/will-linley.jpg",
          },
          {
            id: "t21-3",
            title: "Quite Like Us...",
            audioUrl: "/audio/songs/Quite Like Us-will-linley.mp3",
            coverArt: "/images/artists/will-linley.jpg",
          },
          {
            id: "t21-4",
            title: "First Love",
            audioUrl: "/audio/songs/First Love-will-linley.mp3",
            coverArt: "/images/artists/will-linley.jpg",
          },
          {
            id: "t21-5",
            title: "How It Starts",
            audioUrl: "/audio/songs/How It Starts-will-linley.mp3",
            coverArt: "/images/artists/will-linley.jpg",
          },
          {
            id: "t21-6",
            title: "I Loved, I Lost",
            audioUrl: "/audio/songs/I Loved, I Lost-will-linley.mp3",
            coverArt: "/images/artists/will-linley.jpg",
          },
        ],
      },
    ],
  }),

  getters: {
    allArtists: (state) => state.artistsList,
    getArtistById: (state) => (id) => {
      return state.artistsList.find((artist) => artist.id === id);
    },
  },

  namespaced: true,
};
