import { apiRequest } from "../services/api";

const knownImageSlugs = new Set([
  "a-reece", "alice-phoebe-lou", "bongeziwe-mabandla", "hunter-rose",
  "internet-girl", "moonchild-sanelly", "the-parlotones", "usimamane",
  "vigro-deep", "will-linley"
]);
const imageFor = (name) => {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  return knownImageSlugs.has(slug) ? `/images/artists/${slug}.jpg` : null;
};
const mapArtist = (artist) => ({
  ...artist, name: artist.stageName, genre: artist.genres || [],
  image: artist.avatarUrl || imageFor(artist.stageName),
  tracks: artist.tracks || [], albums: artist.albums || []
});

export default {
  state: () => ({
    artistsList: [
      {
        id: "1",
        name: "Alice Phoebe Lou",
        handle: "alicephoebelou",
        genre: ["Indie Pop", "Indie Folk", "Alternative"],
        location: "Berlin / Cape Town",
        image: "/images/artists/alice-phoebe-lou.jpg",
        bio: "Independent singer-songwriter known for her soulful vocals and dreamy indie-folk sound.",
        tracks: [
          { id: "t1-1", title: "Witches", audioUrl: null },
          { id: "t1-2", title: "Open My Door", audioUrl: null },
          { id: "t1-3", title: "Touch", audioUrl: null },
          { id: "t1-4", title: "Only When I", audioUrl: null },
          { id: "t1-5", title: "Angel", audioUrl: null },
          { id: "t1-6", title: "Lover // Over the Moon", audioUrl: null },
        ],
      },
      {
        id: "2",
        name: "A-Reece",
        handle: "areeecsa",
        genre: ["Hip-Hop"],
        location: "Pretoria",
        image: "/images/artists/a-reece.jpg",
        bio: "Prolific lyricist and leading figure in South African hip hop.",
        tracks: [
          { id: "t2-1", title: "Four Horsemen", audioUrl: null },
          { id: "t2-2", title: "Activity", audioUrl: null },
          { id: "t2-3", title: "Pavlovian Effect", audioUrl: null },
          { id: "t2-4", title: "Bojack", audioUrl: null },
          { id: "t2-5", title: "Confused Admiration", audioUrl: null },
          { id: "t2-6", title: "Idgaf", audioUrl: null },
        ],
      },
      {
        id: "3",
        name: "Bongeziwe Mabandla",
        handle: "bongeziwe",
        genre: ["Folk"],
        location: "Johannesburg",
        image: "/images/artists/bongeziwe-mabandla.jpg",
        bio: "Acclaimed Afro-folk artist celebrated for his emotive storytelling and Xhosa lyrics.",
        tracks: [
          { id: "t3-1", title: "Ndokulandela", audioUrl: null },
          { id: "t3-2", title: "salanabani (13.8.18)", audioUrl: null },
          { id: "t3-3", title: "masiziyekelele (14.11.16)", audioUrl: null },
          { id: "t3-4", title: "mini esadibana ngayo (#001)", audioUrl: null },
          { id: "t3-5", title: "jikeleza", audioUrl: null },
          { id: "t3-6", title: "Yini", audioUrl: null },
        ],
      },
      {
        id: "4",
        name: "Brendan Peyper",
        handle: "brendanpeyper",
        genre: ["Pop", "Contemporary Country"],
        location: "Bloemfontein",
        image: "/images/artists/brendan-peyper.jpg",
        bio: "Energetic singer-songwriter blending modern pop appeal with country-rock elements.",
        tracks: [
          { id: "t4-1", title: "H2Hart", audioUrl: null },
          { id: "t4-2", title: "Sarie Marais", audioUrl: null },
          { id: "t4-3", title: "Rooi Vlag", audioUrl: null },
          { id: "t4-4", title: "Kyk", audioUrl: null },
          { id: "t4-5", title: "Lentelyf (Omdat Jy Mag)", audioUrl: null },
          { id: "t4-6", title: "Soen Soos Wat Jy Dans", audioUrl: null },
        ],
      },
      {
        id: "5",
        name: "Civil Twilight",
        handle: "civiltwilight",
        genre: ["Alternative Rock", "Art Rock", "Indie Rock"],
        location: "Johannesburg",
        image: "/images/artists/civil-spotlight.jpg",
        bio: "Independent alternative rock group delivering heavy riffs and dynamic hooks.",
        tracks: [
          { id: "t5-1", title: "Quiet In My Town", audioUrl: null },
          { id: "t5-2", title: "Come As You Are", audioUrl: null },
          { id: "t5-3", title: "Holy Dove", audioUrl: null },
          { id: "t5-4", title: "The Courage Of The Fall", audioUrl: null },
          { id: "t5-5", title: "Holy Weather", audioUrl: null },
          { id: "t5-6", title: "Fire Escape", audioUrl: null },
        ],
      },
      {
        id: "6",
        name: "CrashCarBurn",
        handle: "crashcarburn",
        genre: ["Pop-punk", "Power Pop", "Alternative Rock"],
        location: "Johannesburg",
        image: "/images/artists/crashcarburn.jpg",
        bio: "Veteran South African rock band known for high-octane performances.",
        tracks: [
          { id: "t6-1", title: "Serenade", audioUrl: null },
          { id: "t6-2", title: "Long Live Tonight", audioUrl: null },
          { id: "t6-3", title: "Free Fallin'", audioUrl: null },
          { id: "t6-4", title: "Stay", audioUrl: null },
          { id: "t6-5", title: "Don't Break", audioUrl: null },
          { id: "t6-6", title: "Don't It Feel Good?", audioUrl: null },
        ],
      },
      {
        id: "7",
        name: "Da Capo",
        handle: "dacapo",
        genre: ["Dance/Electronic", "Amapiano"],
        location: "Polokwane",
        image: "/images/artists/da-capo.jpg",
        bio: "Renowned DJ and producer shaping the deep house and afro-house landscape globally.",
        tracks: [
          { id: "t7-1", title: "Secret ID", audioUrl: null },
          { id: "t7-2", title: "Afrika", audioUrl: null },
          { id: "t7-3", title: "Dancing In The Villa", audioUrl: null },
          { id: "t7-4", title: "I Choose To Stay", audioUrl: null },
          { id: "t7-5", title: "Meet Me In Africa", audioUrl: null },
          {
            id: "t7-6",
            title: "A Prayer For All My Countrymen",
            audioUrl: null,
          },
        ],
      },
      {
        id: "8",
        name: "Halo Yagami",
        handle: "haloyagami",
        genre: ["Experimental R&B", "Soul"],
        location: "Johannesburg",
        image: "/images/artists/halo-yagami.jpg",
        bio: "Innovative artist pushing the boundaries of sound design and modern rap.",
        tracks: [
          { id: "t8-1", title: "Uyikhokonke", audioUrl: null },
          { id: "t8-2", title: "432", audioUrl: null },
          { id: "t8-3", title: "Nyamazane", audioUrl: null },
          { id: "t8-4", title: "Alive", audioUrl: null },
          { id: "t8-5", title: "Phresha", audioUrl: null },
          { id: "t8-6", title: "Safari", audioUrl: null },
        ],
      },
      {
        id: "9",
        name: "Hunter Rose",
        handle: "hunterrose",
        genre: ["Soul", "Jazz", "R&B"],
        location: "Cape Town",
        image: "/images/artists/hunter-rose.jpg",
        bio: "Sensational R&B vocal talent delivering lush harmonies and groovy beats.",
        tracks: [
          { id: "t9-1", title: "Seaside Dreams", audioUrl: null },
          { id: "t9-2", title: "Love Birds", audioUrl: null },
          { id: "t9-3", title: "Fine Wine", audioUrl: null },
          { id: "t9-4", title: "TONIGHT?", audioUrl: null },
          { id: "t9-5", title: "CITY", audioUrl: null },
          { id: "t9-6", title: "TIME", audioUrl: null },
        ],
      },
      {
        id: "10",
        name: "Internet Girl",
        handle: "internetgirl",
        genre: ["Indie", "Garage-Rock"],
        location: "South Africa",
        image: "/images/artists/internet-girl.jpg",
        bio: "Genre-bending underground collective crafting glitchy, high-energy alt sounds.",
        tracks: [
          { id: "t10-1", title: "PULL UP", audioUrl: null },
          { id: "t10-2", title: "I CHANGED (I'M UP)", audioUrl: null },
          { id: "t10-3", title: "COKEHEAD", audioUrl: null },
          { id: "t10-4", title: "F all ur Friends", audioUrl: null },
          { id: "t10-5", title: "NEEDY", audioUrl: null },
          { id: "t10-6", title: "dumb party", audioUrl: null },
        ],
      },
      {
        id: "11",
        name: "Jamali",
        handle: "jamali",
        genre: ["R&B", "Afropop"],
        location: "Johannesburg",
        image: "/images/artists/jamali.jpg",
        bio: "Iconic South African pop-R&B trio celebrated for timeless vocal harmonies.",
        tracks: [
          { id: "t11-1", title: "Maisha", audioUrl: null },
          { id: "t11-2", title: "Incurable", audioUrl: null },
          { id: "t11-3", title: "Yours Fatally", audioUrl: null },
          { id: "t11-4", title: "Skut Julle Lywe", audioUrl: null },
          { id: "t11-5", title: "Secrets", audioUrl: null },
          { id: "t11-6", title: "Everytime", audioUrl: null },
        ],
      },
      {
        id: "12",
        name: "Lordkez",
        handle: "lordkez",
        genre: ["R&B", "Neo-Soul"],
        location: "Johannesburg",
        image: "/images/artists/lordkez.jpg",
        bio: "Versatile singer, songwriter, and poet creating introspective, moody soundscapes.",
        tracks: [
          { id: "t12-1", title: "Aweh", audioUrl: null },
          { id: "t12-2", title: "4SHO", audioUrl: null },
          { id: "t12-3", title: "belladonna", audioUrl: null },
          { id: "t12-4", title: "Enthralled", audioUrl: null },
          { id: "t12-5", title: "Confessions", audioUrl: null },
          { id: "t12-6", title: "22", audioUrl: null },
        ],
      },
      {
        id: "13",
        name: "Moonchild Sanelly",
        handle: "moonchildsanelly",
        genre: ["Future Ghetto Funk"],
        location: "Johannesburg",
        image: "/images/artists/moonchild-sanelly.jpg",
        bio: "Globally acclaimed singer and dancer known for her signature blue hair and high-energy persona.",
        tracks: [
          { id: "t13-1", title: "Demon", audioUrl: null },
          { id: "t13-2", title: "With Love To An Ex", audioUrl: null },
          { id: "t13-3", title: "Big Man", audioUrl: null },
          { id: "t13-4", title: "UYABALABALA", audioUrl: null },
          { id: "t13-5", title: "Falling", audioUrl: null },
          { id: "t13-6", title: "MY POWER", audioUrl: null },
        ],
      },
      {
        id: "14",
        name: "Springbok Nude Girls",
        handle: "springboknudegirls",
        genre: ["Alternative Rock", "Pop-Rock"],
        location: "Stellenbosch",
        image: "/images/artists/springbok-nude-girls.jpg",
        bio: "Legendary South African rock heavyweights pioneering alternative music since the 90s.",
        tracks: [
          { id: "t14-1", title: "Blue Eyes", audioUrl: null },
          { id: "t14-2", title: "Genie", audioUrl: null },
          { id: "t14-3", title: "Bubblegum On My Boots", audioUrl: null },
          { id: "t14-4", title: "Giant Love Affair", audioUrl: null },
          { id: "t14-5", title: "Get the Picture", audioUrl: null },
          { id: "t14-6", title: "SA Tan On The Beaches", audioUrl: null },
        ],
      },
      {
        id: "15",
        name: "The Black Cat Bones",
        handle: "theblackcatbones",
        genre: ["Rock", "Blues", "Country", "Folk"],
        location: "Pretoria",
        image: "/images/artists/the-black-cat-bones.jpg",
        bio: "Raw, gritty blues-rock outfit delivering high-power authentic musicianship.",
        tracks: [
          { id: "t15-1", title: "Hemingway", audioUrl: null },
          { id: "t15-2", title: "Dearly Beloved", audioUrl: null },
          { id: "t15-3", title: "Don't Wake The Scarecrow", audioUrl: null },
          { id: "t15-4", title: "When I See You", audioUrl: null },
          { id: "t15-5", title: "Black Cat Bone", audioUrl: null },
          { id: "t15-6", title: "The Well", audioUrl: null },
        ],
      },
      {
        id: "16",
        name: "The Dirty Skirts",
        handle: "thedirtyskirts",
        genre: ["Indie Rock", "Alternative Rock"],
        location: "Cape Town",
        image: "/images/artists/the-dirty-skirts.jpg",
        bio: "Award-winning indie rock band famous for electrifying live shows and anthemic hooks.",
        tracks: [
          { id: "t16-1", title: "Daddy Don't Disco", audioUrl: null },
          { id: "t16-2", title: "Strike The Match", audioUrl: null },
          { id: "t16-3", title: "Home Wrecker", audioUrl: null },
          { id: "t16-4", title: "Rolling Like Thunder", audioUrl: null },
          { id: "t16-5", title: "Can't Remember Your Name", audioUrl: null },
          { id: "t16-6", title: "Evil Comes", audioUrl: null },
        ],
      },
      {
        id: "17",
        name: "The Parlotones",
        handle: "theparlotones",
        genre: ["Indie Rock", "Alternative Rock", "Pop Rock"],
        location: "Johannesburg",
        image: "/images/artists/the-parlotones.jpg",
        bio: "Multi-platinum selling indie rock band with iconic cinematic sound and grand melodic structures.",
        tracks: [
          { id: "t17-1", title: "Colourful", audioUrl: null },
          { id: "t17-2", title: "I'll Be There", audioUrl: null },
          { id: "t17-3", title: "Giant Mistake", audioUrl: null },
          { id: "t17-4", title: "I'm Only Human", audioUrl: null },
          { id: "t17-5", title: "Life In a Jar", audioUrl: null },
          { id: "t17-6", title: "Come Together", audioUrl: null },
        ],
      },
      {
        id: "18",
        name: "Usimamane",
        handle: "usimamane",
        genre: ["Hip-Hop/Rap"],
        location: "Durban",
        image: "/images/artists/usimamane.jpg",
        bio: "Pioneering new wave rap artist from South Africa making massive waves.",
        tracks: [
          { id: "t18-1", title: "Soft", audioUrl: null },
          { id: "t18-2", title: "Anthem", audioUrl: null },
          { id: "t18-3", title: "Wola (feat. Lorx)", audioUrl: null },
          { id: "t18-4", title: "Star", audioUrl: null },
          { id: "t18-5", title: "21", audioUrl: null },
          { id: "t18-6", title: "Uphambene", audioUrl: null },
        ],
      },
      {
        id: "19",
        name: "Vigro Deep",
        handle: "vigrodeep",
        genre: ["Amapiano"],
        location: "Pretoria",
        image: "/images/artists/vigro-deep.jpg",
        bio: "Child prodigy and trailblazing producer driving the evolution of Amapiano.",
        tracks: [
          { id: "t19-1", title: "Bhampa", audioUrl: null },
          { id: "t19-2", title: "Ghost Producer", audioUrl: null },
          { id: "t19-3", title: "Uyaganga 2.0", audioUrl: null },
          { id: "t19-4", title: "Nomsa", audioUrl: null },
          { id: "t19-5", title: "Mandebi", audioUrl: null },
          { id: "t19-6", title: "There's Alot Going On", audioUrl: null },
        ],
      },
      {
        id: "20",
        name: "Walk These Skies",
        handle: "walktheseskies",
        genre: ["Modern Metalcore", "Deathcore"],
        location: "Cape Town",
        image: "/images/artists/walk-these-skies.jpg",
        bio: "Melodic rock group known for soaring guitar leads and emotional intensity.",
        tracks: [
          { id: "t20-1", title: "Godforsaken", audioUrl: null },
          { id: "t20-2", title: "The Bottom", audioUrl: null },
          { id: "t20-3", title: "Cyanide Milkshake", audioUrl: null },
          { id: "t20-4", title: "All The Same", audioUrl: null },
          { id: "t20-5", title: "Condemned", audioUrl: null },
          { id: "t20-6", title: "Tetracycline Injection", audioUrl: null },
        ],
      },
      {
        id: "21",
        name: "Will Linley",
        handle: "willlinley",
        genre: ["Pop"],
        location: "Cape Town",
        image: "/images/artists/will-linley.jpg",
        bio: "Viral pop singer-songwriter crafting infectious, heartfelt pop tracks.",
        tracks: [
          { id: "t21-1", title: "Last Call", audioUrl: null },
          { id: "t21-2", title: "Holding The Line", audioUrl: null },
          { id: "t21-3", title: "Quite Like Us...", audioUrl: null },
          { id: "t21-4", title: "First Love", audioUrl: null },
          { id: "t21-5", title: "How It Starts", audioUrl: null },
          { id: "t21-6", title: "I Loved, I Lost", audioUrl: null },
        ],
      },
    ],
  }),

  getters: {
    allArtists: (state) => state.artistsList,
    getArtistById: (state) => (id) => {
      return state.artistsList.find((artist) => String(artist.id) === String(id));
    },
  },

  mutations: {
    SET_ARTISTS(state, artists) { state.artistsList = artists; },
    UPSERT_ARTIST(state, artist) {
      const index = state.artistsList.findIndex((item) => String(item.id) === String(artist.id));
      if (index === -1) state.artistsList.push(artist);
      else state.artistsList.splice(index, 1, artist);
    }
  },

  actions: {
    async fetchArtists({ commit }) {
      const { artists } = await apiRequest("/api/artists?limit=100");
      const mapped = artists.map(mapArtist); commit("SET_ARTISTS", mapped); return mapped;
    },
    async fetchArtist({ commit }, id) {
      const { artist } = await apiRequest(`/api/artists/${id}`);
      const mapped = mapArtist(artist); commit("UPSERT_ARTIST", mapped); return mapped;
    }
  },

  namespaced: true,
};
